import * as fs from 'node:fs';
import * as path from 'node:path';
import { PrerequisiteError } from '../types/errors.js';
import { forbiddenArtifacts } from '../types/change.js';
import { readConfig, resolveBasePaths, resolveKnowledgeTokenBudget } from '../lib/config.js';
import type { KnowledgeSizeBudget } from '../types/config.js';
import { readChangeMetadata, readScaleQuietly } from '../lib/change-metadata.js';
import { resolveChange } from './change-resolver.js';
import { scanDir, filterConventions, moduleScanPatterns } from '../lib/scanner.js';
import { renderTemplate } from '../lib/template.js';
import { hasAutoBlock, replaceAutoBlock } from '../lib/content-merger.js';
import { deriveKeyExports } from '../lib/key-exports.js';
import { atomicWrite, ensureDir, readFileIfExists } from '../lib/fs-utils.js';
import { parseYaml, parseYamlDocument, stringifyYamlDocument, mergeIntoDocument } from '../lib/yaml-utils.js';
import { isSafeResourceName, loadFeatureMap, sweepModuleReadme } from '../lib/knowledge-reader.js';
import type { ModuleMap } from '../types/module-map.js';
import type { FeatureMap } from '../types/feature-map.js';
import { buildIndexTemplateContext } from '../lib/index-template.js';
import { buildIndexTable, backfillCuratedFromIndex, type IndexRowModule } from '../lib/index-table.js';

// --- Interfaces (Task 5: REQ-SERVICES-023) ---

export interface KnowledgeUpdateOptions {
  /** Path to delta-spec.md (auto mode) */
  deltaSpecPath?: string;
  /** Manual module names to update (manual mode) */
  manualModules?: string[];
  /** Working directory */
  cwd?: string;
  /**
   * metadata.related_modules of the change — the reliable affected-module set
   * used to resolve feature-prefixed REQ ids (e.g. REQ-MCP-*) whose prefix is a
   * feature, not a module. Ignored for module-prefix REQ ids.
   */
  relatedModules?: string[];
}

export interface DeltaReqEntry {
  /** REQ ID (e.g., REQ-SERVICES-020) */
  id: string;
  /** Module name extracted from REQ ID (e.g., services) */
  module: string;
  /** Requirement title/description */
  description: string;
}

export interface DeltaSpecResult {
  added: DeltaReqEntry[];
  modified: DeltaReqEntry[];
  removed: DeltaReqEntry[];
  /**
   * REQ-shaped headings that fail the canonical `REQ-MODULE-NNN` form (a 3-digit
   * sequence, per delta-spec-format.md). Surfaced rather than silently dropped,
   * so a non-conforming id reported elsewhere is not invisibly skipped here.
   */
  malformed: string[];
}

export interface GeneratedFile {
  path: string;
  action: 'created' | 'updated' | 'deprecated';
}

export interface KnowledgeUpdateResult {
  /** Modules that were created (ADDED) */
  created: string[];
  /** Modules acknowledged as MODIFIED — their index/module-map rows are
   *  refreshed, but their README content is NOT touched (see readmePending). */
  updated: string[];
  /** Modules that were marked deprecated (REMOVED) */
  deprecated: string[];
  /** Modules whose README content update is the SKILL's judgment work — an
   *  existing README is never regenerated by this service (issue #107). */
  readmePending: string[];
  /** All generated/modified file paths */
  generatedFiles: GeneratedFile[];
  /** Non-fatal notices — e.g. non-canonical REQ ids skipped during parsing. */
  warnings: string[];
  /** Result of Phase 3a Sweep */
  sweptFiles: Array<{ module: string; savings: number }>;
}

// --- Delta Spec Parser (Task 6: REQ-SERVICES-020) ---

/**
 * Parse delta-spec.md content into structured ADDED/MODIFIED/REMOVED entries.
 *
 * Extracts REQ IDs (REQ-{MODULE}-{NNN}) and maps them to module names.
 * Returns empty arrays for malformed or empty input (never throws).
 */
export function parseDeltaSpec(content: string): DeltaSpecResult {
  const result: DeltaSpecResult = { added: [], modified: [], removed: [], malformed: [] };

  if (!content || !content.trim()) {
    return result;
  }

  const lines = content.split('\n');
  let currentSection: 'added' | 'modified' | 'removed' | null = null;

  for (const line of lines) {
    // Detect section headers
    const sectionMatch = line.match(/^##\s+(ADDED|MODIFIED|REMOVED)/i);
    if (sectionMatch) {
      currentSection = sectionMatch[1]!.toLowerCase() as 'added' | 'modified' | 'removed';
      continue;
    }

    // Canonical REQ heading: ### REQ-{MODULE}-{NNN} with a 3-digit sequence.
    const reqMatch = line.match(/^###\s+(REQ-([\w-]+)-\d{3}):\s*(.*)/);
    if (reqMatch && currentSection) {
      result[currentSection].push({
        id: reqMatch[1]!,
        module: reqMatch[2]!.toLowerCase(),
        description: reqMatch[3]!.trim(),
      });
      continue;
    }

    // A REQ-shaped heading that is NOT canonical (wrong digit count, missing
    // module segment, …) is surfaced, not silently dropped — the looser parsers
    // in archive.service may route it, so this keeps the two sides honest.
    const malformedMatch = line.match(/^###\s+(REQ-[\w-]+):/);
    if (malformedMatch && currentSection) {
      result.malformed.push(malformedMatch[1]!);
    }
  }

  return result;
}

// --- Module README Update (Task 8: REQ-SERVICES-021) ---

/**
 * Create a skeleton README for a NEW module — and only then.
 *
 * An existing README is never rewritten: this repo's module knowledge lives
 * INSIDE the `prospec:auto` block, and re-rendering that block from the
 * mechanical scan context (a `"<name> module"` description, heuristic file
 * descriptions) guts the LLM-authored content — the very reason
 * archive.service was decoupled from this service (2026-07-05). README
 * content updates are judgment and stay with the skill; callers report such
 * modules as readme-pending. Returns null when the README already exists.
 */
export async function updateModuleReadme(
  moduleName: string,
  modulePaths: string[],
  options: { cwd: string; knowledgeBasePath: string; excludePatterns?: string[] },
): Promise<GeneratedFile | null> {
  const readmePath = path.join(
    options.cwd,
    options.knowledgeBasePath,
    'modules',
    moduleName,
    'README.md',
  );

  if (fs.existsSync(readmePath)) return null;

  await ensureDir(path.dirname(readmePath));

  // Scan module files
  const patterns =
    modulePaths.length > 0
      ? moduleScanPatterns(modulePaths, options.cwd)
      : [`${moduleName}/**`];
  const scanResult = await scanDir(patterns, {
    cwd: options.cwd,
    exclude: options.excludePatterns ?? [],
  });

  const keyFiles = scanResult.files.slice(0, 20).map((filePath) => ({
    path: filePath,
    description: inferFileDescription(filePath),
  }));

  // Render fresh README content (Recipe-First format)
  const templateContext = {
    module_name: moduleName,
    description: `${moduleName} module`,
    path: modulePaths[0] ?? moduleName,
    keywords: [],
    relationships: { depends_on: [], used_by: [] },
    key_files: keyFiles.slice(0, 10),
    key_exports: deriveKeyExports(keyFiles),
  };

  const newContent = renderTemplate('knowledge/module-readme.hbs', templateContext);
  await atomicWrite(readmePath, newContent);

  return {
    path: path.join(options.knowledgeBasePath, 'modules', moduleName, 'README.md'),
    action: 'created',
  };
}

// --- Phase 3a Sweep (Task 7) ---

export async function applyReadmeSweep(
  moduleName: string,
  options: { cwd: string; knowledgeBasePath: string },
): Promise<{ savings: number } | null> {
  const readmePath = path.join(
    options.cwd,
    options.knowledgeBasePath,
    'modules',
    moduleName,
    'README.md',
  );
  const existingContent = await readFileIfExists(readmePath);
  if (!existingContent) return null;
  const { swept, savings } = sweepModuleReadme(existingContent);
  if (savings > 0 || swept !== existingContent) {
    await atomicWrite(readmePath, swept);
  }
  return { savings };
}

// --- Mark Module Deprecated (Task 9: REQ-SERVICES-021) ---

/**
 * Add a deprecation banner to a module's README.md.
 * Does NOT delete the file — only marks as deprecated.
 */
export async function markModuleDeprecated(
  moduleName: string,
  reason: string,
  options: { cwd: string; knowledgeBasePath: string },
): Promise<GeneratedFile | null> {
  const readmePath = path.join(
    options.cwd,
    options.knowledgeBasePath,
    'modules',
    moduleName,
    'README.md',
  );

  // If README doesn't exist, nothing to deprecate
  try {
    await fs.promises.access(readmePath);
  } catch {
    return null;
  }

  const content = await fs.promises.readFile(readmePath, 'utf-8');

  // Don't add duplicate deprecation banners
  if (content.includes('> **DEPRECATED**')) {
    return { path: path.join(options.knowledgeBasePath, 'modules', moduleName, 'README.md'), action: 'deprecated' };
  }

  const banner = `> **DEPRECATED**: This module was removed. Reason: ${reason}\n\n`;
  const updatedContent = banner + content;

  await atomicWrite(readmePath, updatedContent);

  return {
    path: path.join(options.knowledgeBasePath, 'modules', moduleName, 'README.md'),
    action: 'deprecated',
  };
}

// --- Index Update (Task 10: REQ-SERVICES-022) ---

/**
 * Update index.md module table within prospec:auto-start/end markers.
 */
export async function updateIndex(
  modules: IndexRowModule[],
  options: {
    cwd: string;
    baseDir: string;
    knowledgeBasePath: string;
    projectName: string;
    techStack?: { language?: string; framework?: string; package_manager?: string };
    additionalCore?: string[];
    // Resolved by the caller: updateIndex takes an options bag, not the config, and
    // the loading-rules table it renders needs one number per budget field.
    tokenBudget: KnowledgeSizeBudget;
  },
): Promise<GeneratedFile> {
  const indexPath = path.join(options.cwd, options.baseDir, 'index.md');
  await ensureDir(path.dirname(indexPath));

  const conventionScan = await scanDir('_*.md', { cwd: path.join(options.cwd, options.knowledgeBasePath) });
  const { core, demand } = filterConventions(conventionScan.files, options.additionalCore);

  // Render every column from module-map data (the single source) — curated
  // columns (Keywords/Aliases/Rationale, Depends On via relationships.depends_on)
  // are preserved, never blanked to `—`. Header/separator/cell order derive from
  // the canonical schema in types/knowledge.ts.
  const modulesTable = buildIndexTable(modules);

  // One context feeds both branches below AND the other index emitters
  // (init / knowledge init) via the shared partial, so the auto block can never
  // drift from knowledge/index.md.hbs.
  const templateContext = buildIndexTemplateContext({
    projectName: options.projectName,
    techStack: options.techStack,
    baseDir: options.baseDir,
    knowledgeBasePath: options.knowledgeBasePath,
    coreConventions: core,
    demandConventions: demand,
    tokenBudget: options.tokenBudget,
    modulesTable,
  });

  // Read existing index.md for in-place auto-block replacement
  // (read-or-empty; non-ENOENT errors propagate).
  const existingContent = await readFileIfExists(indexPath);
  const action: GeneratedFile['action'] = existingContent ? 'updated' : 'created';

  let finalContent: string;
  if (existingContent && hasAutoBlock(existingContent)) {
    // Replace ONLY the auto block in place; preserve all curated content.
    // replaceAutoBlock uses a function replacer so `$`-sequences in module
    // descriptions (the table cells) are inserted verbatim.
    const autoBlock = `<!-- prospec:auto-start -->
${renderTemplate('knowledge/_index-auto-block.hbs', templateContext).trimEnd()}
<!-- prospec:auto-end -->`;
    finalContent = replaceAutoBlock(existingContent, autoBlock);
  } else {
    // Create (or a marker-less file): emit the full canonical document.
    finalContent = renderTemplate('knowledge/index.md.hbs', templateContext);
  }

  await atomicWrite(indexPath, finalContent);

  return {
    path: path.join(options.baseDir, 'index.md'),
    action,
  };
}

// --- Module Map Update (Task 11: REQ-SERVICES-022) ---

/**
 * Update module-map.yaml: add new modules, remove deprecated ones.
 * Gracefully skips if module-map.yaml doesn't exist.
 */
export async function updateModuleMap(
  changes: { added: string[]; removed: string[] },
  moduleMapPath: string,
): Promise<GeneratedFile | null> {
  // Graceful skip if module-map.yaml doesn't exist
  try {
    await fs.promises.access(moduleMapPath);
  } catch {
    return null;
  }

  const content = await fs.promises.readFile(moduleMapPath, 'utf-8');
  const moduleMap = parseYaml<ModuleMap>(content, moduleMapPath);
  const before = JSON.stringify(moduleMap.modules);

  // Add new modules
  for (const name of changes.added) {
    const exists = moduleMap.modules.some(
      (m) => m.name.toLowerCase() === name.toLowerCase(),
    );
    if (!exists) {
      moduleMap.modules.push({
        name,
        description: `${name} module`,
        paths: [`src/${name}/**`],
        keywords: [name],
      });
    }
  }

  // Remove deprecated modules
  if (changes.removed.length > 0) {
    const removedSet = new Set(changes.removed.map((n) => n.toLowerCase()));
    moduleMap.modules = moduleMap.modules.filter(
      (m) => !removedSet.has(m.name.toLowerCase()),
    );
  }

  // No-op when nothing actually changed — the curated file must not be
  // rewritten (and reflowed) just because the coordinator called through.
  if (JSON.stringify(moduleMap.modules) === before) return null;

  // Comment-preserving in-place merge: module-map.yaml is a CURATED file whose
  // header comments document the dependency rule. A full `stringifyYaml`
  // round-trip drops every comment and reflows untouched descriptions, so the
  // merge goes through the yaml Document (same path writeConfig uses).
  const doc = parseYamlDocument(content, moduleMapPath);
  mergeIntoDocument(doc, moduleMap as unknown as Record<string, unknown>);
  await atomicWrite(moduleMapPath, stringifyYamlDocument(doc));

  return {
    path: moduleMapPath,
    action: 'updated',
  };
}

// --- Execute Orchestrator (Task 12: REQ-SERVICES-023) ---

/**
 * Main knowledge-update execution flow.
 *
 * Supports two modes:
 * 1. deltaSpecPath: reads and parses delta-spec.md, identifies affected modules
 * 2. manualModules: accepts module name array, updates only those modules' READMEs
 */
export async function execute(
  options: KnowledgeUpdateOptions,
): Promise<KnowledgeUpdateResult> {
  const cwd = options.cwd ?? process.cwd();

  // Read config
  const config = await readConfig(cwd);
  const { knowledgePath, baseDir } = resolveBasePaths(config, cwd);
  const baseDirPath = path.relative(cwd, baseDir).replace(/\\/g, '/');
  const knowledgeBasePath = path.relative(cwd, knowledgePath).replace(/\\/g, '/');
  const excludePatterns = config.exclude ?? [];
  const projectName = config.project.name;
  const moduleMapPath = path.join(knowledgePath, 'module-map.yaml');

  const result: KnowledgeUpdateResult = {
    created: [],
    updated: [],
    deprecated: [],
    readmePending: [],
    generatedFiles: [],
    warnings: [],
    sweptFiles: [],
  };

  const baseOpts = { cwd, knowledgeBasePath, excludePatterns };

  if (options.deltaSpecPath) {
    // --- Delta Spec Mode ---
    const deltaContent = await fs.promises.readFile(options.deltaSpecPath, 'utf-8');
    const delta = parseDeltaSpec(deltaContent);
    if (delta.malformed.length > 0) {
      result.warnings.push(
        `Skipped ${delta.malformed.length} non-canonical REQ id(s) ` +
          `(expected REQ-MODULE-NNN with a 3-digit sequence): ${delta.malformed.join(', ')}`,
      );
    }

    // Resolve module paths from module-map.yaml
    const modulePathMap = buildModulePathMap(moduleMapPath);
    const knownModules = collectKnownModules(modulePathMap, knowledgePath);
    const featureMap = loadFeatureMap(knowledgePath);
    const relatedModules = (options.relatedModules ?? []).map((m) => m.toLowerCase());

    // Map a delta REQ entry to the module(s) whose README it should sync.
    // A module-prefix REQ maps to that one module (legacy behavior, incl. the
    // src/<name>/** fallback for a genuinely new module). A feature-prefix REQ
    // (its prefix is a feature-map req_prefix, NOT a module — e.g. REQ-MCP) is
    // re-mapped to that feature's modules ∪ related_modules, intersected with
    // known modules — never minting a phantom modules/<prefix>/ (BL-043).
    const resolveEntryModules = (entry: DeltaReqEntry): string[] => {
      if (knownModules.has(entry.module)) return [entry.module];
      const featureModules = featurePrefixModules(featureMap, entry.module);
      if (featureModules === null) return [entry.module]; // a module name, not a feature prefix
      const resolved = [...new Set([...featureModules, ...relatedModules])].filter((m) =>
        knownModules.has(m),
      );
      if (resolved.length === 0) {
        result.warnings.push(
          `${entry.id}: "${entry.module}" is a feature prefix, not a module — set ` +
            `metadata.related_modules (or feature-map modules) so the change can sync ` +
            `(skipped; no module minted)`,
        );
      }
      return resolved;
    };

    // Removal wins: a module that is also REMOVED must not be created/updated
    // (its README would be regenerated then immediately deprecated, and it would
    // be falsely reported as both updated and deprecated).
    const removedModules = new Set(delta.removed.map((e) => e.module));
    const addedSynced = new Set<string>();

    // Process ADDED modules — a genuinely new module gets a skeleton README
    // for the skill to fill; an ADDED entry resolving to an existing module
    // (its README already exists) becomes readme-pending judgment work.
    for (const entry of delta.added) {
      for (const mod of resolveEntryModules(entry)) {
        if (removedModules.has(mod)) continue;
        const paths = modulePathMap.get(mod) ?? [`src/${mod}/**`];
        const file = await updateModuleReadme(mod, paths, baseOpts);
        if (file) {
          result.generatedFiles.push(file);
          if (!result.created.includes(mod)) result.created.push(mod);
        } else if (!result.readmePending.includes(mod) && !result.created.includes(mod)) {
          result.readmePending.push(mod);
        }
        addedSynced.add(mod);
      }
    }

    // Process MODIFIED modules — README content is the skill's judgment work
    // (never regenerated here; see updateModuleReadme). The module is still
    // acknowledged so its index/module-map rows refresh below.
    for (const entry of delta.modified) {
      for (const mod of resolveEntryModules(entry)) {
        if (removedModules.has(mod)) continue;
        if (!result.updated.includes(mod) && !result.created.includes(mod)) {
          result.updated.push(mod);
        }
        if (!result.readmePending.includes(mod) && !result.created.includes(mod)) {
          result.readmePending.push(mod);
        }
      }
    }

    // Run sweep on affected modules (added but already existed + modified)
    const uniqueAffected = [...new Set([...result.readmePending, ...result.updated])];
    for (const mod of uniqueAffected) {
      const sweepRes = await applyReadmeSweep(mod, baseOpts);
      if (sweepRes) {
        result.sweptFiles.push({ module: mod, savings: sweepRes.savings });
      }
    }

    // Process REMOVED modules — a feature-prefix REMOVED (e.g. REQ-MCP) is not a
    // module, so markModuleDeprecated no-ops on it (no modules/<prefix>/ README);
    // shared modules are never deprecated because one feature's REQ was removed.
    for (const entry of delta.removed) {
      const file = await markModuleDeprecated(
        entry.module,
        entry.description,
        { cwd, knowledgeBasePath },
      );
      if (file) {
        result.generatedFiles.push(file);
        result.deprecated.push(entry.module);
      }
    }

    // Update module-map.yaml — only modules actually synced (feature-prefix-resolved
    // modules are already known, so updateModuleMap no-ops on them; a genuinely new
    // module-prefix module is added as before).
    const uniqueAdded = [...addedSynced];
    const uniqueRemoved = [...new Set(delta.removed.map((e) => e.module))];
    if (uniqueAdded.length > 0 || uniqueRemoved.length > 0) {
      const mapFile = await updateModuleMap(
        { added: uniqueAdded, removed: uniqueRemoved },
        moduleMapPath,
      );
      if (mapFile) {
        result.generatedFiles.push(mapFile);
      }
    }
  } else if (options.manualModules && options.manualModules.length > 0) {
    // --- Manual Mode --- (create-only: an existing README is judgment work)
    // Manual names come straight from --module and drive ensureDir/atomicWrite
    // under modules/<name>/ — unlike delta-spec mode they are not regex-constrained,
    // so a traversal-shaped name must be refused before anything is written.
    const unsafeModules = options.manualModules.filter((m) => !isSafeResourceName(m));
    if (unsafeModules.length > 0) {
      throw new PrerequisiteError(
        `Invalid module name(s): ${unsafeModules.join(', ')}`,
        'A module name must match [A-Za-z0-9][A-Za-z0-9._-]* with no path separators or ".." — use the names declared in module-map.yaml',
      );
    }
    const modulePathMap = buildModulePathMap(moduleMapPath);

    for (const moduleName of options.manualModules) {
      const paths = modulePathMap.get(moduleName.toLowerCase()) ?? [`src/${moduleName}/**`];
      const file = await updateModuleReadme(moduleName, paths, baseOpts);
      if (file) {
        result.generatedFiles.push(file);
        result.created.push(moduleName);
      } else {
        result.updated.push(moduleName);
        result.readmePending.push(moduleName);
      }
    }
  }

  // Migrate curated columns into module-map (the single source) before rebuilding
  // the index. A project that curated Keywords/Aliases/Rationale/Description in
  // index.md gets them seeded into module-map on the fly — no-clobber (never
  // overwrites a non-empty module-map value) and idempotent — so the rebuilt
  // index preserves them instead of blanking to `—`.
  const existingIndex = await readFileIfExists(path.join(cwd, baseDirPath, 'index.md'));
  if (existingIndex && fs.existsSync(moduleMapPath)) {
    try {
      const moduleMap = parseYaml<ModuleMap>(fs.readFileSync(moduleMapPath, 'utf-8'), moduleMapPath);
      const { moduleMap: migrated, changed } = backfillCuratedFromIndex(existingIndex, moduleMap);
      if (changed) {
        const doc = parseYamlDocument(fs.readFileSync(moduleMapPath, 'utf-8'), moduleMapPath);
        mergeIntoDocument(doc, migrated as unknown as Record<string, unknown>);
        await atomicWrite(moduleMapPath, stringifyYamlDocument(doc));
      }
    } catch {
      // Backfill is a non-fatal migration convenience — a malformed module-map
      // or index must not block the index rebuild below.
    }
  }

  // Update index.md with all known modules (module-map now holds curated columns)
  const allModules = collectAllModules(result, moduleMapPath);
  if (allModules.length > 0) {
    const indexFile = await updateIndex(allModules, {
      cwd,
      baseDir: baseDirPath,
      knowledgeBasePath,
      projectName,
      techStack: config.tech_stack,
      additionalCore: config.knowledge?.additional_core_conventions ?? [],
      tokenBudget: resolveKnowledgeTokenBudget(config),
    });
    result.generatedFiles.push(indexFile);
  }

  return result;
}

// --- Change-oriented entry (`prospec knowledge update`) ---

export interface KnowledgeUpdateForChangeOptions {
  /** Explicit change name; resolved interactively when omitted. */
  change?: string;
  /** Manual module names — bypasses change resolution entirely. */
  modules?: string[];
  cwd?: string;
  quiet?: boolean;
}

export interface KnowledgeUpdateForChangeResult extends KnowledgeUpdateResult {
  /** The change whose delta-spec drove the update (absent in manual mode). */
  changeName?: string;
}

/**
 * Resolve a change's delta-spec.md (+ its metadata.related_modules for
 * feature-prefix REQ resolution) and run the incremental update — the wiring
 * `prospec knowledge update` exposes. `--module` skips the change entirely
 * (manual mode).
 */
export async function executeForChange(
  options: KnowledgeUpdateForChangeOptions,
): Promise<KnowledgeUpdateForChangeResult> {
  const cwd = options.cwd ?? process.cwd();

  if (options.modules && options.modules.length > 0) {
    return await execute({ cwd, manualModules: options.modules });
  }

  const changeName = await resolveChange(
    cwd,
    options.change,
    options.quiet,
    'Which change should drive the knowledge update?',
  );
  const changeDir = path.join(cwd, '.prospec', 'changes', changeName);
  const deltaSpecPath = path.join(changeDir, 'delta-spec.md');
  if (!fs.existsSync(deltaSpecPath)) {
    // Only offer the plan station to a scale whose contract allows one — sending
    // a quick change there names a station that refuses it.
    const scale = readScaleQuietly(path.join(changeDir, 'metadata.yaml'), changeName);
    throw new PrerequisiteError(
      `delta-spec.md not found for change '${changeName}'`,
      forbiddenArtifacts(scale).includes('delta-spec.md')
        ? `\`scale: ${scale}\` has no delta-spec by contract — name the modules explicitly with --module`
        : 'A change with no delta-spec yet — name the modules explicitly with --module, or run `prospec change plan` first',
    );
  }
  const { metadata } = readChangeMetadata(path.join(changeDir, 'metadata.yaml'), changeName);

  const result = await execute({
    cwd,
    deltaSpecPath,
    relatedModules: metadata.related_modules ?? [],
  });
  return { ...result, changeName };
}

// --- Internal helpers ---

function buildModulePathMap(moduleMapPath: string): Map<string, string[]> {
  const pathMap = new Map<string, string[]>();
  try {
    const content = fs.readFileSync(moduleMapPath, 'utf-8');
    const moduleMap = parseYaml<ModuleMap>(content, moduleMapPath);
    for (const entry of moduleMap.modules) {
      pathMap.set(entry.name.toLowerCase(), entry.paths);
    }
  } catch {
    // module-map.yaml doesn't exist — return empty map
  }
  return pathMap;
}

/** Known modules = module-map names ∪ existing modules/<name>/ directories (lowercased). */
function collectKnownModules(
  modulePathMap: Map<string, string[]>,
  knowledgePath: string,
): Set<string> {
  const known = new Set<string>(modulePathMap.keys());
  try {
    for (const e of fs.readdirSync(path.join(knowledgePath, 'modules'), { withFileTypes: true })) {
      if (e.isDirectory()) known.add(e.name.toLowerCase());
    }
  } catch {
    // no modules/ directory yet — module-map keys are the known set
  }
  return known;
}

/**
 * Lowercased modules of every feature whose declared req_prefixes include this
 * prefix (case-insensitive). Returns null when the prefix is NOT any feature's
 * req_prefix — the caller then treats it as a module name, not a feature prefix.
 */
function featurePrefixModules(featureMap: FeatureMap | null, prefix: string): string[] | null {
  if (featureMap === null) return null;
  const want = prefix.toUpperCase();
  const modules = new Set<string>();
  let matched = false;
  for (const f of featureMap.features) {
    if ((f.req_prefixes ?? []).some((p) => p.toUpperCase() === want)) {
      matched = true;
      for (const m of f.modules) modules.add(m.toLowerCase());
    }
  }
  return matched ? [...modules] : null;
}

export function collectAllModules(
  result: KnowledgeUpdateResult,
  moduleMapPath: string,
): IndexRowModule[] {
  const modules: IndexRowModule[] = [];

  // result.deprecated holds lowercased delta-spec module names; module-map
  // entry.name is canonical-case. Compare case-insensitively (as updateModuleMap
  // and buildModulePathMap already do) so a mixed-case module isn't mislabeled.
  const deprecatedSet = new Set(result.deprecated.map((n) => n.toLowerCase()));

  // Try reading existing module-map for known modules. module-map.yaml is the
  // single source for the curated columns (keywords/aliases/rationale, and
  // Depends On via relationships.depends_on) — carry them through so updateIndex
  // renders them instead of blanking to `—`.
  try {
    const content = fs.readFileSync(moduleMapPath, 'utf-8');
    const moduleMap = parseYaml<ModuleMap>(content, moduleMapPath);
    for (const entry of moduleMap.modules) {
      const isDeprecated = deprecatedSet.has(entry.name.toLowerCase());
      modules.push({
        name: entry.name,
        description: entry.description ?? `${entry.name} module`,
        status: isDeprecated ? 'Deprecated' : 'Active',
        keywords: entry.keywords ?? [],
        aliases: entry.aliases ?? [],
        rationale: entry.rationale ?? '',
        dependsOn: entry.relationships?.depends_on ?? [],
      });
    }
  } catch {
    // Fallback: use result data only (curated columns unknown → left empty).
    for (const name of [...result.created, ...result.updated]) {
      modules.push({ name, description: `${name} module`, status: 'Active', keywords: [], aliases: [], rationale: '', dependsOn: [] });
    }
    for (const name of result.deprecated) {
      modules.push({ name, description: `${name} module`, status: 'Deprecated', keywords: [], aliases: [], rationale: '', dependsOn: [] });
    }
  }

  return modules;
}

function inferFileDescription(filePath: string): string {
  const basename = path.basename(filePath);
  const ext = path.extname(filePath);

  if (basename === 'index.ts' || basename === 'index.js') return 'Module entry point';
  if (basename.endsWith('.test.ts') || basename.endsWith('.spec.ts')) return 'Test file';
  if (basename.endsWith('.service.ts')) return 'Service implementation';
  if (basename.endsWith('.controller.ts')) return 'Controller implementation';
  if (basename.endsWith('.types.ts')) return 'Type definitions';
  if (basename.endsWith('.utils.ts')) return 'Utility functions';
  if (basename.endsWith('.hbs')) return 'Handlebars template';

  const extDescriptions: Record<string, string> = {
    '.ts': 'TypeScript source',
    '.js': 'JavaScript source',
    '.md': 'Documentation',
    '.yaml': 'YAML configuration',
    '.yml': 'YAML configuration',
    '.json': 'JSON configuration',
  };

  return extDescriptions[ext] ?? 'Source file';
}
