import * as fs from 'node:fs';
import * as path from 'node:path';
import { PrerequisiteError } from '../types/errors.js';
import { forbiddenArtifacts } from '../types/change.js';
import { readConfig, resolveBasePaths, resolveKnowledgeTokenBudget } from '../lib/config.js';
import type { KnowledgeSizeBudget } from '../types/config.js';
import { isProvenBackfill, readChangeMetadata, readScaleQuietly } from '../lib/change-metadata.js';
import { resolveChange } from './change-resolver.js';
import { scanDir, filterConventions, moduleScanPatterns } from '../lib/scanner.js';
import { renderTemplate } from '../lib/template.js';
import { hasAutoBlock, replaceAutoBlock } from '../lib/content-merger.js';
import { deriveKeyExports } from '../lib/key-exports.js';
import { atomicWrite, ensureDir, readFileIfExists } from '../lib/fs-utils.js';
import { parseYaml, parseYamlDocument, stringifyYamlDocument, mergeIntoDocument } from '../lib/yaml-utils.js';
import {
  isSafeResourceName,
  loadModuleMap,
  readContainedText,
  resolveContainedTarget,
  sweepModuleReadme,
} from '../lib/knowledge-reader.js';
import { applicableModuleReadmeExtensions, parseModuleReadmeExtensions } from '../lib/module-readme-format.js';
import { changedPathsFromWorkTree, partitionDiffAttributedModules } from '../lib/drift-sources.js';
import type { ModuleMap } from '../types/module-map.js';
import { buildIndexTemplateContext } from '../lib/index-template.js';
import { buildIndexTable, backfillCuratedFromIndex, type IndexRowModule } from '../lib/index-table.js';
import {
  buildModulePathMap,
  classifyDeltaSpec,
  loadDeltaModuleContext,
  readKnownModules,
  type ClassifiedDeltaEntry,
} from '../lib/knowledge-sync.js';

// --- Interfaces (Task 5: REQ-SERVICES-023) ---

export interface KnowledgeUpdateOptions {
  /** Path to delta-spec.md (auto mode) */
  deltaSpecPath?: string;
  /** Manual module names to update (manual mode) */
  manualModules?: string[];
  /** Working directory */
  cwd?: string;
  /**
   * metadata.related_modules of the change — the reliable affected-module set
   * used to resolve feature-prefixed REQ ids (e.g. REQ-MCP-*) whose prefix is a
   * feature, not a module. Ignored for module-prefix REQ ids.
   */
  relatedModules?: string[];
  /**
   * The change is a proven backfill (`isProvenBackfill`): its feature-slug REQ ids
   * resolve through their `**Feature:**` header instead of minting a module.
   */
  backfill?: boolean;
}

export interface GeneratedFile {
  path: string;
  action: 'created' | 'updated' | 'deprecated';
}

export interface KnowledgeUpdateResult {
  /** Modules that were created (ADDED) */
  created: string[];
  /** Modules acknowledged as MODIFIED — their index/module-map rows are
   *  refreshed, but their README content is NOT touched (see readmePending). */
  updated: string[];
  /** Modules that were marked deprecated (REMOVED) */
  deprecated: string[];
  /** Modules whose README content update is the SKILL's judgment work — an
   *  existing README is never regenerated by this service (issue #107). */
  readmePending: string[];
  /** All generated/modified file paths */
  generatedFiles: GeneratedFile[];
  /** Non-fatal notices — e.g. non-canonical REQ ids skipped during parsing. */
  warnings: string[];
  /** Result of Phase 3a Sweep */
  sweptFiles: Array<{ module: string; savings: number }>;
}

// --- Write targets (REQ-SERVICES-023) ---

/**
 * The real path a knowledge file is read and written at, or a refusal: the same
 * file the contained readers see, so an in-root symlink keeps its link.
 */
function containedTarget(
  filePath: string,
  root: string,
  label: string,
  rootLabel: string,
  options: { read?: boolean } = {},
): string {
  const target = resolveContainedTarget(filePath, root, options);
  if (target.ok) return target.path;
  if (target.reason === 'unobservable') {
    const { code, blockedAt } = target;
    throw new PrerequisiteError(
      `${blockedAt} cannot be looked up for ${label} (${code}) — nothing was written`,
      `fix ${blockedAt} so ${label} resolves, then re-run \`prospec knowledge update\``,
    );
  }
  if (target.danglingLink) {
    const link = target.danglingLink;
    throw new PrerequisiteError(
      `${link} is a symlink whose target does not exist — nothing was written`,
      `restore the target of ${link} or remove the link, then re-run \`prospec knowledge update\``,
    );
  }
  if (target.reason === 'escaped') {
    throw new PrerequisiteError(
      `${label} resolves outside the ${rootLabel} — nothing was written`,
      `keep ${label} inside the ${rootLabel} instead of linking outside it, then re-run \`prospec knowledge update\``,
    );
  }
  if (target.reason === 'no-read-access') {
    throw new PrerequisiteError(
      `${label} cannot be read — nothing was written`,
      `grant read permission on ${label}, then re-run \`prospec knowledge update\``,
    );
  }
  throw new PrerequisiteError(
    `${label} is not a regular file — nothing was written`,
    `replace ${label} with a regular file, then re-run \`prospec knowledge update\``,
  );
}

function readmeTarget(
  moduleName: string,
  options: { cwd: string; knowledgeBasePath: string },
  read: boolean,
): string {
  const knowledgePath = path.resolve(options.cwd, options.knowledgeBasePath);
  return containedTarget(
    path.join(knowledgePath, 'modules', moduleName, 'README.md'),
    knowledgePath,
    `modules/${moduleName}/README.md`,
    'knowledge root',
    { read },
  );
}

/** `index.md` is always read before it is rewritten (curated backfill, auto-block splice). */
function indexTarget(cwd: string, baseDir: string): string {
  const baseDirAbs = path.resolve(cwd, baseDir);
  return containedTarget(path.join(baseDirAbs, 'index.md'), baseDirAbs, 'index.md', 'base directory', {
    read: true,
  });
}

// --- Module README Update (Task 8: REQ-SERVICES-021) ---

/**
 * Create a skeleton README for a NEW module — and only then.
 *
 * An existing README is never rewritten: this repo's module knowledge lives
 * INSIDE the `prospec:auto` block, and re-rendering that block from the
 * mechanical scan context (a `"<name> module"` description, heuristic file
 * descriptions) guts the LLM-authored content — the very reason
 * archive.service was decoupled from this service (2026-07-05). README
 * content updates are judgment and stay with the skill; callers report such
 * modules as readme-pending. Returns null when the README already exists.
 */
export async function updateModuleReadme(
  moduleName: string,
  modulePaths: string[],
  options: { cwd: string; knowledgeBasePath: string; excludePatterns?: string[]; warnings?: string[] },
): Promise<GeneratedFile | null> {
  const readmePath = readmeTarget(moduleName, options, false);

  if (fs.existsSync(readmePath)) return null;

  const knowledgePath = path.resolve(options.cwd, options.knowledgeBasePath);
  const convention = readContainedText(
    path.join(knowledgePath, '_module-readme-conventions.md'),
    knowledgePath,
  );
  const parsedRegistry = convention === null ? null : parseModuleReadmeExtensions(convention);
  if (parsedRegistry && !parsedRegistry.ok) {
    // Fail safe (skeleton without extensions) but not silently: a broken registry
    // would otherwise drop even required extensions with no trace here.
    options.warnings?.push(
      `module '${moduleName}': Project Section Extensions registry has errors — skeleton omits extensions until \`prospec validate module-readme\` reports them fixed`,
    );
  }
  const sectionExtensions = parsedRegistry?.ok
    ? applicableModuleReadmeExtensions(parsedRegistry.declarations, moduleName).map((extension) => ({
      id: extension.id,
      heading: extension.heading,
      placeholder: extension.contentFormat === 'field-table'
        ? '| Field | Value |\n| --- | --- |\n| _Add field_ | _Add value_ |'
        : '_Add content_',
    }))
    : [];

  await ensureDir(path.dirname(readmePath));

  // Scan module files
  const patterns =
    modulePaths.length > 0
      ? moduleScanPatterns(modulePaths, options.cwd)
      : [`${moduleName}/**`];
  const scanResult = await scanDir(patterns, {
    cwd: options.cwd,
    exclude: options.excludePatterns ?? [],
  });

  const keyFiles = scanResult.files.slice(0, 20).map((filePath) => ({
    path: filePath,
    description: inferFileDescription(filePath),
  }));

  // Render fresh README content (Recipe-First format)
  const templateContext = {
    module_name: moduleName,
    description: `${moduleName} module`,
    path: modulePaths[0] ?? moduleName,
    keywords: [],
    relationships: { depends_on: [], used_by: [] },
    key_files: keyFiles.slice(0, 10),
    key_exports: deriveKeyExports(keyFiles),
    section_extensions: sectionExtensions,
  };

  const newContent = renderTemplate('knowledge/module-readme.hbs', templateContext);
  await atomicWrite(readmePath, newContent);

  return {
    path: path.join(options.knowledgeBasePath, 'modules', moduleName, 'README.md'),
    action: 'created',
  };
}

// --- Phase 3a Sweep (Task 7) ---

export async function applyReadmeSweep(
  moduleName: string,
  options: { cwd: string; knowledgeBasePath: string },
): Promise<{ savings: number } | null> {
  const readmePath = readmeTarget(moduleName, options, true);
  const existingContent = await readFileIfExists(readmePath);
  if (!existingContent) return null;
  const { swept, savings } = sweepModuleReadme(existingContent);
  if (savings > 0 || swept !== existingContent) {
    await atomicWrite(readmePath, swept);
  }
  return { savings };
}

// --- Mark Module Deprecated (Task 9: REQ-SERVICES-021) ---

/**
 * Add a deprecation banner to a module's README.md.
 * Does NOT delete the file — only marks as deprecated.
 */
export async function markModuleDeprecated(
  moduleName: string,
  reason: string,
  options: { cwd: string; knowledgeBasePath: string },
): Promise<GeneratedFile | null> {
  const readmePath = readmeTarget(moduleName, options, true);

  // If README doesn't exist, nothing to deprecate
  try {
    await fs.promises.access(readmePath);
  } catch {
    return null;
  }

  const content = await fs.promises.readFile(readmePath, 'utf-8');

  // Don't add duplicate deprecation banners
  if (content.includes('> **DEPRECATED**')) {
    return { path: path.join(options.knowledgeBasePath, 'modules', moduleName, 'README.md'), action: 'deprecated' };
  }

  const banner = `> **DEPRECATED**: This module was removed. Reason: ${reason}\n\n`;
  const updatedContent = banner + content;

  await atomicWrite(readmePath, updatedContent);

  return {
    path: path.join(options.knowledgeBasePath, 'modules', moduleName, 'README.md'),
    action: 'deprecated',
  };
}

// --- Index Update (Task 10: REQ-SERVICES-022) ---

/**
 * Update index.md module table within prospec:auto-start/end markers.
 */
export async function updateIndex(
  modules: IndexRowModule[],
  options: {
    cwd: string;
    baseDir: string;
    knowledgeBasePath: string;
    projectName: string;
    techStack?: { language?: string; framework?: string; package_manager?: string };
    additionalCore?: string[];
    // Resolved by the caller: updateIndex takes an options bag, not the config, and
    // the loading-rules table it renders needs one number per budget field.
    tokenBudget: KnowledgeSizeBudget;
  },
): Promise<GeneratedFile> {
  const indexPath = indexTarget(options.cwd, options.baseDir);
  await ensureDir(path.dirname(indexPath));

  const conventionScan = await scanDir('_*.md', { cwd: path.join(options.cwd, options.knowledgeBasePath) });
  const { core, demand } = filterConventions(conventionScan.files, options.additionalCore);

  // Render every column from module-map data (the single source) — curated
  // columns (Keywords/Aliases/Rationale, Depends On via relationships.depends_on)
  // are preserved, never blanked to `—`. Header/separator/cell order derive from
  // the canonical schema in types/knowledge.ts.
  const modulesTable = buildIndexTable(modules);

  // One context feeds both branches below AND the other index emitters
  // (init / knowledge init) via the shared partial, so the auto block can never
  // drift from knowledge/index.md.hbs.
  const templateContext = buildIndexTemplateContext({
    projectName: options.projectName,
    techStack: options.techStack,
    baseDir: options.baseDir,
    knowledgeBasePath: options.knowledgeBasePath,
    coreConventions: core,
    demandConventions: demand,
    tokenBudget: options.tokenBudget,
    modulesTable,
  });

  // Read existing index.md for in-place auto-block replacement
  // (read-or-empty; non-ENOENT errors propagate).
  const existingContent = await readFileIfExists(indexPath);
  const action: GeneratedFile['action'] = existingContent ? 'updated' : 'created';

  let finalContent: string;
  if (existingContent && hasAutoBlock(existingContent)) {
    // Replace ONLY the auto block in place; preserve all curated content.
    // replaceAutoBlock uses a function replacer so `$`-sequences in module
    // descriptions (the table cells) are inserted verbatim.
    const autoBlock = `<!-- prospec:auto-start -->
${renderTemplate('knowledge/_index-auto-block.hbs', templateContext).trimEnd()}
<!-- prospec:auto-end -->`;
    finalContent = replaceAutoBlock(existingContent, autoBlock);
  } else {
    // Create (or a marker-less file): emit the full canonical document.
    finalContent = renderTemplate('knowledge/index.md.hbs', templateContext);
  }

  await atomicWrite(indexPath, finalContent);

  return {
    path: path.join(options.baseDir, 'index.md'),
    action,
  };
}

// --- Module Map Update (Task 11: REQ-SERVICES-022) ---

/**
 * Update module-map.yaml: add new modules, remove deprecated ones.
 * Gracefully skips if module-map.yaml doesn't exist.
 */
export async function updateModuleMap(
  changes: { added: string[]; removed: string[] },
  moduleMapPath: string,
): Promise<GeneratedFile | null> {
  // Graceful skip if module-map.yaml doesn't exist (or cannot be read inside its own directory)
  const content = readContainedText(moduleMapPath, path.dirname(moduleMapPath));
  const target = resolveContainedTarget(moduleMapPath, path.dirname(moduleMapPath));
  if (content === null || !target.ok) return null;

  const moduleMap = parseYaml<ModuleMap>(content, moduleMapPath);
  const before = JSON.stringify(moduleMap.modules);

  // Add new modules
  for (const name of changes.added) {
    const exists = moduleMap.modules.some(
      (m) => m.name.toLowerCase() === name.toLowerCase(),
    );
    if (!exists) {
      moduleMap.modules.push({
        name,
        description: `${name} module`,
        paths: [`src/${name}/**`],
        keywords: [name],
      });
    }
  }

  // Remove deprecated modules
  if (changes.removed.length > 0) {
    const removedSet = new Set(changes.removed.map((n) => n.toLowerCase()));
    moduleMap.modules = moduleMap.modules.filter(
      (m) => !removedSet.has(m.name.toLowerCase()),
    );
  }

  // No-op when nothing actually changed — the curated file must not be
  // rewritten (and reflowed) just because the coordinator called through.
  if (JSON.stringify(moduleMap.modules) === before) return null;

  // Comment-preserving in-place merge: module-map.yaml is a CURATED file whose
  // header comments document the dependency rule. A full `stringifyYaml`
  // round-trip drops every comment and reflows untouched descriptions, so the
  // merge goes through the yaml Document (same path writeConfig uses).
  const doc = parseYamlDocument(content, moduleMapPath);
  mergeIntoDocument(doc, moduleMap as unknown as Record<string, unknown>);
  await atomicWrite(target.path, stringifyYamlDocument(doc));

  return {
    path: moduleMapPath,
    action: 'updated',
  };
}

// --- Execute Orchestrator (Task 12: REQ-SERVICES-023) ---

/**
 * Main knowledge-update execution flow.
 *
 * Supports two modes:
 * 1. deltaSpecPath: reads and parses delta-spec.md, identifies affected modules
 * 2. manualModules: accepts module name array, updates only those modules' READMEs
 */
export async function execute(
  options: KnowledgeUpdateOptions,
): Promise<KnowledgeUpdateResult> {
  const cwd = options.cwd ?? process.cwd();

  // Read config
  const config = await readConfig(cwd);
  const { knowledgePath, baseDir } = resolveBasePaths(config, cwd);
  const baseDirPath = path.relative(cwd, baseDir).replace(/\\/g, '/');
  const knowledgeBasePath = path.relative(cwd, knowledgePath).replace(/\\/g, '/');
  const excludePatterns = config.exclude ?? [];
  const projectName = config.project.name;
  const moduleMapPath = path.join(knowledgePath, 'module-map.yaml');

  const result: KnowledgeUpdateResult = {
    created: [],
    updated: [],
    deprecated: [],
    readmePending: [],
    generatedFiles: [],
    warnings: [],
    sweptFiles: [],
  };

  const baseOpts = { cwd, knowledgeBasePath, excludePatterns, warnings: result.warnings };

  // Every mode reads or rewrites the map below, and without a trustworthy one every
  // delta-spec REQ would classify as "not a module"; refuse before anything is written.
  const { unreadable } = readKnownModules(knowledgePath, cwd);
  if (unreadable) {
    throw new PrerequisiteError(
      `${unreadable.cause} — ${options.deltaSpecPath ? 'no delta-spec REQ was classified' : 'nothing was written'}`,
      `${unreadable.remedy}, then re-run \`prospec knowledge update\``,
    );
  }

  // Manual names come straight from --module and drive ensureDir/atomicWrite
  // under modules/<name>/ — unlike delta-spec mode they are not regex-constrained,
  // so a traversal-shaped name must be refused before anything is written.
  const manualModules = options.deltaSpecPath ? [] : options.manualModules ?? [];
  const unsafeModules = manualModules.filter((m) => !isSafeResourceName(m));
  if (unsafeModules.length > 0) {
    throw new PrerequisiteError(
      `Invalid module name(s): ${unsafeModules.join(', ')}`,
      'A module name must match [A-Za-z0-9][A-Za-z0-9._-]* with no path separators or ".." — use the names declared in module-map.yaml',
    );
  }

  // Judge every target before the first write, so a refusal leaves nothing half-written.
  const indexPath = indexTarget(cwd, baseDirPath);
  const mapPath = containedTarget(moduleMapPath, knowledgePath, 'module-map.yaml', 'knowledge root');
  // delta mode sweeps every existing README it touches; manual mode only creates missing ones
  const preflightReadmes = (modules: Iterable<string>, read: boolean): void => {
    for (const mod of modules) readmeTarget(mod, baseOpts, read);
  };

  if (options.deltaSpecPath) {
    // --- Delta Spec Mode ---
    const deltaContent = await fs.promises.readFile(options.deltaSpecPath, 'utf-8');
    // The knowledge-sync gate classifies the same entries through the same context,
    // so the modules acknowledged here are the modules the gate checks.
    const ctx = loadDeltaModuleContext(knowledgePath, options.relatedModules ?? [], options.backfill ?? false);
    const modulePathMap = ctx.modulePaths;
    const entries = classifyDeltaSpec(deltaContent, ctx);
    preflightReadmes(entries.flatMap((e) => e.modules), true);
    const malformed = entries.filter((e) => e.kind === 'malformed').map((e) => e.id);
    if (malformed.length > 0) {
      result.warnings.push(
        `Skipped ${malformed.length} non-canonical REQ id(s) ` +
          `(expected REQ-MODULE-NNN with a 3-digit sequence): ${malformed.join(', ')}`,
      );
    }
    const added = entries.filter((e) => e.section === 'added' && e.kind !== 'malformed');
    const modified = entries.filter((e) => e.section === 'modified' && e.kind !== 'malformed');
    const removed = entries.filter((e) => e.section === 'removed' && e.kind !== 'malformed');

    // A feature prefix or backfill slug that resolves to no known module is skipped,
    // never minted as a phantom modules/<prefix>/ (BL-043); a MODIFIED REQ with an
    // unknown non-feature prefix names no module at all.
    const modulesToSync = (entry: ClassifiedDeltaEntry): string[] => {
      if (entry.kind === 'feature' && entry.modules.length === 0) {
        result.warnings.push(
          `${entry.id}: "${entry.prefix}" is a feature prefix, not a module — record the modules ` +
            `with \`prospec change related-modules <module...>\` (or in the feature-map feature) so the ` +
            `change can sync (skipped; no module minted)`,
        );
      } else if (entry.kind === 'feature-slug' && entry.modules.length === 0) {
        result.warnings.push(
          `${entry.id}: "${entry.prefix}" is a backfill feature slug with no known module — record ` +
            `the modules with \`prospec change related-modules <module...>\` so the change can sync ` +
            `(skipped; no module minted)`,
        );
      } else if (entry.kind === 'ignored') {
        result.warnings.push(
          `${entry.id}: "${entry.prefix}" is neither a known module nor a feature prefix — ` +
            `skipped (only an ADDED REQ can name a new module)`,
        );
      }
      return entry.modules;
    };

    const addedSynced = new Set<string>();

    // Process ADDED modules — a genuinely new module gets a skeleton README
    // for the skill to fill; an ADDED entry resolving to an existing module
    // (its README already exists) becomes readme-pending judgment work.
    for (const entry of added) {
      for (const mod of modulesToSync(entry)) {
        const paths = modulePathMap.get(mod) ?? [`src/${mod}/**`];
        const file = await updateModuleReadme(mod, paths, baseOpts);
        if (file) {
          result.generatedFiles.push(file);
          if (!result.created.includes(mod)) result.created.push(mod);
        } else if (!result.readmePending.includes(mod) && !result.created.includes(mod)) {
          result.readmePending.push(mod);
        }
        addedSynced.add(mod);
      }
    }

    // Process MODIFIED and REMOVED modules — README content is the skill's judgment
    // work (never regenerated here; see updateModuleReadme). A REMOVED REQ takes
    // behavior out of its module's README; it never deprecates or unregisters the
    // module, which the knowledge-sync gate goes on checking.
    for (const entry of [...modified, ...removed]) {
      for (const mod of modulesToSync(entry)) {
        if (!result.updated.includes(mod) && !result.created.includes(mod)) {
          result.updated.push(mod);
        }
        if (!result.readmePending.includes(mod) && !result.created.includes(mod)) {
          result.readmePending.push(mod);
        }
      }
    }

    // Run sweep on affected modules (added but already existed + modified)
    const uniqueAffected = [...new Set([...result.readmePending, ...result.updated])];
    for (const mod of uniqueAffected) {
      const sweepRes = await applyReadmeSweep(mod, baseOpts);
      if (sweepRes) {
        result.sweptFiles.push({ module: mod, savings: sweepRes.savings });
      }
    }

    // Update module-map.yaml — only modules actually synced (feature-prefix-resolved
    // modules are already known, so updateModuleMap no-ops on them; a genuinely new
    // module-prefix module is added as before).
    const uniqueAdded = [...addedSynced];
    if (uniqueAdded.length > 0) {
      const mapFile = await updateModuleMap({ added: uniqueAdded, removed: [] }, moduleMapPath);
      if (mapFile) {
        result.generatedFiles.push(mapFile);
      }
    }
  } else if (manualModules.length > 0) {
    // --- Manual Mode --- (create-only: an existing README is judgment work)
    preflightReadmes(manualModules, false);
    const modulePathMap = buildModulePathMap(knowledgePath) ?? new Map<string, string[]>();

    for (const moduleName of manualModules) {
      const paths = modulePathMap.get(moduleName.toLowerCase()) ?? [`src/${moduleName}/**`];
      const file = await updateModuleReadme(moduleName, paths, baseOpts);
      if (file) {
        result.generatedFiles.push(file);
        result.created.push(moduleName);
      } else {
        result.updated.push(moduleName);
        result.readmePending.push(moduleName);
      }
    }
  }

  // Migrate curated columns into module-map (the single source) before rebuilding
  // the index. A project that curated Keywords/Aliases/Rationale/Description in
  // index.md gets them seeded into module-map on the fly — no-clobber (never
  // overwrites a non-empty module-map value) and idempotent — so the rebuilt
  // index preserves them instead of blanking to `—`.
  const existingIndex = await readFileIfExists(indexPath);
  const mapContent = existingIndex ? readContainedText(moduleMapPath, knowledgePath) : null;
  if (existingIndex && mapContent !== null) {
    try {
      const moduleMap = parseYaml<ModuleMap>(mapContent, moduleMapPath);
      const { moduleMap: migrated, changed } = backfillCuratedFromIndex(existingIndex, moduleMap);
      if (changed) {
        const doc = parseYamlDocument(mapContent, moduleMapPath);
        mergeIntoDocument(doc, migrated as unknown as Record<string, unknown>);
        await atomicWrite(mapPath, stringifyYamlDocument(doc));
      }
    } catch {
      // Backfill is a non-fatal migration convenience — a malformed module-map
      // or index must not block the index rebuild below.
    }
  }

  // Update index.md with all known modules (module-map now holds curated columns)
  const allModules = collectAllModules(result, moduleMapPath);
  if (allModules.length > 0) {
    const indexFile = await updateIndex(allModules, {
      cwd,
      baseDir: baseDirPath,
      knowledgeBasePath,
      projectName,
      techStack: config.tech_stack,
      additionalCore: config.knowledge?.additional_core_conventions ?? [],
      tokenBudget: resolveKnowledgeTokenBudget(config),
    });
    result.generatedFiles.push(indexFile);
  }

  return result;
}

// --- Change-oriented entry (`prospec knowledge update`) ---

export interface KnowledgeUpdateForChangeOptions {
  /** Explicit change name; resolved interactively when omitted. */
  change?: string;
  /** Manual module names — bypasses change resolution entirely. */
  modules?: string[];
  cwd?: string;
  quiet?: boolean;
}

export interface KnowledgeUpdateForChangeResult extends KnowledgeUpdateResult {
  /** The change whose delta-spec drove the update (absent in manual mode). */
  changeName?: string;
  /**
   * Modules a working-tree diff attributes but no delta-spec REQ named — typically
   * a generated artifact (a bundled template regenerated under a lib path) pulling
   * in its module. They need only a `knowledge verify` freshness stamp, not a README
   * edit. Always present (empty when nothing qualifies, in manual mode, or when the
   * working tree / module map is unavailable) so the field is a total `string[]`.
   */
  stampOnly: string[];
}

/**
 * Resolve a change's delta-spec.md (+ its metadata.related_modules for
 * feature-prefix REQ resolution) and run the incremental update — the wiring
 * `prospec knowledge update` exposes. `--module` skips the change entirely
 * (manual mode).
 */
export async function executeForChange(
  options: KnowledgeUpdateForChangeOptions,
): Promise<KnowledgeUpdateForChangeResult> {
  const cwd = options.cwd ?? process.cwd();

  if (options.modules && options.modules.length > 0) {
    // Manual mode performs no diff attribution (there is no change context to diff);
    // stampOnly is empty so the return type stays a total KnowledgeUpdateForChangeResult.
    return { ...(await execute({ cwd, manualModules: options.modules })), stampOnly: [] };
  }

  const changeName = await resolveChange(
    cwd,
    options.change,
    options.quiet,
    'Which change should drive the knowledge update?',
  );
  const changeDir = path.join(cwd, '.prospec', 'changes', changeName);
  const deltaSpecPath = path.join(changeDir, 'delta-spec.md');
  if (!fs.existsSync(deltaSpecPath)) {
    // Only offer the plan station to a scale whose contract allows one — sending
    // a quick change there names a station that refuses it.
    const scale = readScaleQuietly(path.join(changeDir, 'metadata.yaml'), changeName);
    throw new PrerequisiteError(
      `delta-spec.md not found for change '${changeName}'`,
      forbiddenArtifacts(scale).includes('delta-spec.md')
        ? `\`scale: ${scale}\` has no delta-spec by contract — name the modules explicitly with --module`
        : 'A change with no delta-spec yet — name the modules explicitly with --module, or run `prospec change plan` first',
    );
  }
  const { metadata } = readChangeMetadata(path.join(changeDir, 'metadata.yaml'), changeName);

  const result = await execute({
    cwd,
    deltaSpecPath,
    relatedModules: metadata.related_modules ?? [],
    backfill: isProvenBackfill(changeDir, metadata.scale),
  });

  // Diff-path attribution (union with the REQ-prefix modules `execute` resolved):
  // a change's working tree may touch a module's source that no delta-spec REQ named
  // — typically a generated artifact (e.g. `pnpm bundle` rewriting a bundled template
  // under a lib path). Those modules need a freshness stamp but no README edit, so
  // report them separately as stamp-only candidates. Advisory: it must never turn the
  // mechanical update into a new failure mode (the CI committed-range gate is the
  // backstop), but the degradation is SCOPED — only git being unavailable falls back
  // to an empty list (`execute` has already refused an unreadable module map); a
  // logic error in the pure partition is NOT swallowed, it propagates.
  let stampOnly: string[] = [];
  const changed = changedPathsFromWorkTree(cwd); // null (fail-closed) on any git failure
  if (changed && changed.length > 0) {
    // Resolve the knowledge path once for this advisory read. It is deliberately
    // independent of execute()'s own config resolution above — one extra parse on a
    // cold, non-hot CLI path is cheaper than widening execute()'s public result
    // contract just to hand the resolved map back.
    const { knowledgePath } = resolveBasePaths(await readConfig(cwd), cwd);
    const moduleMap = loadModuleMap(knowledgePath, cwd);
    if (moduleMap) {
      const reqAcknowledged = [
        ...result.created,
        ...result.updated,
        ...result.readmePending,
        ...result.deprecated,
      ];
      stampOnly = partitionDiffAttributedModules(changed, moduleMap, reqAcknowledged).stampOnly;
    }
  }

  return { ...result, changeName, stampOnly };
}

// --- Internal helpers ---

export function collectAllModules(
  result: KnowledgeUpdateResult,
  moduleMapPath: string,
): IndexRowModule[] {
  const modules: IndexRowModule[] = [];

  // result.deprecated holds lowercased delta-spec module names; module-map
  // entry.name is canonical-case. Compare case-insensitively (as updateModuleMap
  // and buildModulePathMap already do) so a mixed-case module isn't mislabeled.
  const deprecatedSet = new Set(result.deprecated.map((n) => n.toLowerCase()));

  // Try reading existing module-map for known modules. module-map.yaml is the
  // single source for the curated columns (keywords/aliases/rationale, and
  // Depends On via relationships.depends_on) — carry them through so updateIndex
  // renders them instead of blanking to `—`.
  // A map that is absent, unreadable or outside its own directory renders as the fallback.
  const content = readContainedText(moduleMapPath, path.dirname(moduleMapPath));
  if (content === null) return appendResultRows(modules, result);
  try {
    const moduleMap = parseYaml<ModuleMap>(content, moduleMapPath);
    for (const entry of moduleMap.modules) {
      const isDeprecated = deprecatedSet.has(entry.name.toLowerCase());
      modules.push({
        name: entry.name,
        description: entry.description ?? `${entry.name} module`,
        status: isDeprecated ? 'Deprecated' : 'Active',
        keywords: entry.keywords ?? [],
        aliases: entry.aliases ?? [],
        rationale: entry.rationale ?? '',
        dependsOn: entry.relationships?.depends_on ?? [],
        category: entry.category ?? [],
      });
    }
  } catch {
    return appendResultRows(modules, result);
  }

  return modules;
}

/** Fallback rows from result data only (curated columns unknown → left empty). */
function appendResultRows(modules: IndexRowModule[], result: KnowledgeUpdateResult): IndexRowModule[] {
  for (const name of [...result.created, ...result.updated]) {
    modules.push({ name, description: `${name} module`, status: 'Active', keywords: [], aliases: [], rationale: '', dependsOn: [], category: [] });
  }
  for (const name of result.deprecated) {
    modules.push({ name, description: `${name} module`, status: 'Deprecated', keywords: [], aliases: [], rationale: '', dependsOn: [], category: [] });
  }
  return modules;
}

function inferFileDescription(filePath: string): string {
  const basename = path.basename(filePath);
  const ext = path.extname(filePath);

  if (basename === 'index.ts' || basename === 'index.js') return 'Module entry point';
  if (basename.endsWith('.test.ts') || basename.endsWith('.spec.ts')) return 'Test file';
  if (basename.endsWith('.service.ts')) return 'Service implementation';
  if (basename.endsWith('.controller.ts')) return 'Controller implementation';
  if (basename.endsWith('.types.ts')) return 'Type definitions';
  if (basename.endsWith('.utils.ts')) return 'Utility functions';
  if (basename.endsWith('.hbs')) return 'Handlebars template';

  const extDescriptions: Record<string, string> = {
    '.ts': 'TypeScript source',
    '.js': 'JavaScript source',
    '.md': 'Documentation',
    '.yaml': 'YAML configuration',
    '.yml': 'YAML configuration',
    '.json': 'JSON configuration',
  };

  return extDescriptions[ext] ?? 'Source file';
}
