import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export function bundleTemplates() {
  const templatesDir = path.resolve(__dirname, '../src/templates');
  const outputFile = path.resolve(__dirname, '../src/lib/bundled-templates.ts');

  function scanDirectory(dir: string, baseDir: string): Record<string, string> {
    const results: Record<string, string> = {};
    if (!fs.existsSync(dir)) return results;
    const list = fs.readdirSync(dir);
    for (const file of list) {
      const filePath = path.resolve(dir, file);
      const stat = fs.statSync(filePath);
      if (stat.isDirectory()) {
        Object.assign(results, scanDirectory(filePath, baseDir));
      } else if (file.endsWith('.hbs')) {
        const relPath = path.relative(baseDir, filePath).replace(/\\/g, '/');
        const content = fs.readFileSync(filePath, 'utf-8');
        results[relPath] = content;
      }
    }
    return results;
  }

  const templates = scanDirectory(templatesDir, templatesDir);
  const codeContent = `// This file is auto-generated by scripts/bundle-templates.ts. Do not edit.
export const BUNDLED_TEMPLATES: Record<string, string> = ${JSON.stringify(templates, null, 2)};
`;

  fs.writeFileSync(outputFile, codeContent, 'utf-8');
  console.log(`Successfully bundled ${Object.keys(templates).length} templates into ${outputFile}`);
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  bundleTemplates();
}

