/**
 * Fail when the repository's generated artifacts are not what the current
 * templates produce.
 *
 * The contract suite reads `src/templates/**` only, so a template edit that never
 * reached the deployed `.claude/` / `.agents/` trees is invisible to it — every
 * test passes while the `SKILL.md` an agent actually loads still teaches the
 * superseded rule. That gap shipped stale copies twice inside one change.
 *
 * BOTH hops are covered, because `agent sync` renders from `BUNDLED_TEMPLATES` and
 * never reads `src/templates/`: checking only the sync would pass a template edit
 * that was never bundled — which is the FIRST of those two failures. The steps are
 * data (`REGENERATE_STEPS`) rather than inline calls so a baseline test can pin
 * them; dropping one silently re-blinds the gate, and that is precisely what
 * happened to its first draft.
 *
 * Reproducing the render inside a test would need the sync's real context (project
 * name, token budgets, minimum CLI version, localized triggers) and would false-red
 * whenever any differed. So the property checked needs no context at all: running
 * the real pipeline changes nothing. Hash-based rather than git-based on purpose —
 * during a change the deployed tree is legitimately modified-but-uncommitted, and
 * "is it committed" is a different question from "is it current".
 *
 * It WRITES: both steps are the real thing, so a stale tree is repaired in the act
 * of being detected and a second run is green. The failure message says so.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, existsSync, statSync } from 'node:fs';
import path from 'node:path';

/** Deployed agent trees — what an agent actually loads. */
export const AGENT_DIRS = ['.claude', '.agents'];
/** Single files that are themselves generated output. */
export const GENERATED_FILES = ['src/lib/bundled-templates.ts'];
/** Ordered regeneration pipeline. Order matters: the sync renders from the bundle. */
export const REGENERATE_STEPS: ReadonlyArray<readonly string[]> = [
  ['npx', 'tsx', 'scripts/bundle.ts'],
  ['npx', 'tsx', 'src/cli/index.ts', 'agent', 'sync'],
];

export interface ArtifactTargets {
  dirs: string[];
  files: string[];
}

/** Content fingerprint of every generated file, keyed by path. */
export function fingerprint(targets: ArtifactTargets, cwd = process.cwd()): Map<string, string> {
  const out = new Map<string, string>();
  const hash = (rel: string): void => {
    try {
      out.set(rel, createHash('sha256').update(readFileSync(path.join(cwd, rel))).digest('hex'));
    } catch {
      // Unreadable is a fact about the file, not a reason to abort the whole
      // verdict — record it distinctly so it still shows up as a difference.
      out.set(rel, 'UNREADABLE');
    }
  };
  const walk = (rel: string): void => {
    const abs = path.join(cwd, rel);
    if (!existsSync(abs) || !statSync(abs).isDirectory()) return;
    for (const entry of readdirSync(abs, { withFileTypes: true }).sort((a, b) =>
      a.name < b.name ? -1 : 1,
    )) {
      const child = path.join(rel, entry.name);
      if (entry.isDirectory()) walk(child);
      else if (entry.isFile()) hash(child);
    }
  };
  for (const d of targets.dirs) walk(d);
  for (const f of targets.files) if (existsSync(path.join(cwd, f))) hash(f);
  return out;
}

/** Paths whose content the regeneration changed, added or removed. */
export function diffFingerprints(
  before: ReadonlyMap<string, string>,
  after: ReadonlyMap<string, string>,
): string[] {
  return [
    ...[...after]
      .filter(([f, h]) => before.get(f) !== h)
      .map(([f]) => `${before.has(f) ? 'changed' : 'added  '} ${f}`),
    ...[...before.keys()].filter((f) => !after.has(f)).map((f) => `removed ${f}`),
  ].sort();
}

/** Regenerate, then report what moved. `regenerate` is injected so the comparison
 *  is testable without spawning the real toolchain. */
export function checkGeneratedArtifacts(
  targets: ArtifactTargets,
  regenerate: () => void,
  cwd = process.cwd(),
): { changed: string[]; total: number } {
  const before = fingerprint(targets, cwd);
  regenerate();
  const after = fingerprint(targets, cwd);
  return { changed: diffFingerprints(before, after), total: after.size };
}

function main(): void {
  const { changed, total } = checkGeneratedArtifacts(
    { dirs: AGENT_DIRS, files: [...GENERATED_FILES] },
    () => {
      for (const [cmd, ...args] of REGENERATE_STEPS) {
        execFileSync(cmd!, args, { stdio: 'pipe' });
      }
    },
  );
  if (changed.length > 0) {
    console.error('✗ generated artifacts were stale — regenerating changed:');
    for (const line of changed) console.error(`    ${line}`);
    console.error('  they have ALREADY been regenerated by this run, so a second run is green.');
    console.error('  review the diff above and commit it — do not read the next green as a flake.');
    process.exit(1);
  }
  console.log(`✓ generated artifacts are current: templates → bundle → deployed (${total} files)`);
}

if (process.argv[1] !== undefined && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  main();
}
